# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProductMJ2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductMJ2

  pod 'SnapKit'
  pod 'QMUIKit'
  pod 'SVProgressHUD'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'IAPurchaseManager'
  pod 'TZImagePickerController' 

end
